@startuml
'https://plantuml.com/class-diagram


Class Input {
-string Input:
-input numbers: int
}

Class SumLoop {
-int i = 5
- for i > 0, i-1
- int sum = input + sum
}

Class Output{
-printf sum: int
}

SumLoop <-- Input
Output <-- SumLoop
@enduml